"""
Synthetic seed data for development.
RULE: No real PII. All names, phone numbers, and identifiers are generated by Faker.
Run: python -m seed.seed  (from the backend/ directory with DATABASE_URL set)
"""

import asyncio
import random
from datetime import date

from faker import Faker
from sqlalchemy import select, text
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine

from app.config import settings
from app.models.donor import Donor, Organizer
from app.models.facility import Facility
from app.models.auth import User
from app.models.audit import FeatureFlag
from app.models.enums import (
    BloodGroupEnum,
    ComponentTypeEnum,
    DonorStatusEnum,
    OrgCategoryEnum,
    SexEnum,
    UserRoleEnum,
)
from app.models.stock import AlertThreshold as AlertThresholdModel
from app.services.auth import hash_password
fake = Faker("en_IN")
random.seed(42)

BLOOD_GROUPS = list(BloodGroupEnum)
COMPONENT_TYPES = list(ComponentTypeEnum)


async def seed(db: AsyncSession) -> None:
    print("Seeding facilities…")
    facility = Facility(
        name="District Hospital & Red Cross Blood Bank, Durg",
        facility_code="RKDURG",
        type="blood_bank",
        address="Civil Lines, Durg, Chhattisgarh 491001",
        district="Durg",
        state="Chhattisgarh",
        phone="07788-123456",
        is_active=True,
    )
    db.add(facility)
    await db.flush()

    print("Seeding users (one per role)…")
    roles_passwords = [
        (UserRoleEnum.SUPERADMIN, "super123"),
        (UserRoleEnum.DISTRICT_ADMIN, "district123"),
        (UserRoleEnum.DOCTOR, "doctor123"),
        (UserRoleEnum.ORGANIZER, "organizer123"),
        (UserRoleEnum.CITIZEN, "citizen123"),
    ]
    users: dict[UserRoleEnum, User] = {}
    for role, password in roles_passwords:
        user = User(
            facility_id=facility.id if role not in (UserRoleEnum.ORGANIZER, UserRoleEnum.CITIZEN) else None,
            role=role,
            username=f"seed_{role.value}",
            email=f"seed_{role.value}@rakt.local",
            phone=fake.phone_number()[:20],
            hashed_password=hash_password(password),
            display_name=f"Seed {role.value.replace('_', ' ').title()}",
            is_active=True,
        )
        db.add(user)
        users[role] = user
    await db.flush()

    print("Linking citizen to a donor profile…")
    citizen_dob = fake.date_of_birth(minimum_age=18, maximum_age=55)
    citizen_donor = Donor(
        name="Seed Citizen",
        date_of_birth=citizen_dob,
        age_years=(date.today() - citizen_dob).days // 365,
        sex=SexEnum.MALE,
        contact_phone=fake.msisdn()[:20],
        address=fake.address(),
        blood_group=BloodGroupEnum.O_POS,
        status=DonorStatusEnum.ACTIVE,
        consent_given=True,
        consent_purpose="blood_donation_registration",
        registered_at_facility_id=facility.id,
        user_id=users[UserRoleEnum.CITIZEN].id,
        created_by=users[UserRoleEnum.SUPERADMIN].id,
    )
    db.add(citizen_donor)
    await db.flush()

    print("Seeding organizer profile…")
    db.add(
        Organizer(
            user_id=users[UserRoleEnum.ORGANIZER].id,
            org_name="Seed Organizer Society",
            org_type="ngo",
            org_category=OrgCategoryEnum.SOCIAL_ORG,
            contact_name="Seed Organizer",
            contact_role="अध्यक्ष",
            contact_phone=fake.msisdn()[:20],
            contact_email="seed_organizer@rakt.local",
            contact_address="Civil Lines, Durg",
            address="Near District Hospital, Durg",
            is_verified=True,
        )
    )
    await db.flush()

    print("Seeding alert thresholds…")
    for bg in BLOOD_GROUPS:
        for ct in COMPONENT_TYPES:
            threshold = AlertThresholdModel(
                facility_id=facility.id,
                blood_group=bg,
                component_type=ct,
                low_stock_qty=2,
                near_expiry_days=3,
                updated_by=users[UserRoleEnum.SUPERADMIN].id,
            )
            db.add(threshold)

    print("Seeding barcode sequence…")
    await db.execute(
        text(
            "INSERT INTO barcode_sequences (facility_id, last_seq) "
            "VALUES (:fid, 0) ON CONFLICT DO NOTHING"
        ),
        {"fid": str(facility.id)},
    )

    print("Verifying feature flag…")
    flag_result = await db.execute(
        select(FeatureFlag).where(FeatureFlag.name == "wallet_enabled")
    )
    flag = flag_result.scalar_one_or_none()
    if flag is None:
        db.add(FeatureFlag(
            name="wallet_enabled",
            is_enabled=True,
            description="Blood Credit Wallet — enabled in dev seed.",
        ))
    else:
        flag.is_enabled = True

    print("Seeding organizer directory…")
    from seed.organizers_directory import (
        ORGANIZER_ACCOUNT_PASSWORD,
        seed_organizer_accounts,
        seed_organizer_directory,
    )

    dir_count = await seed_organizer_directory(db)
    print(f"  Directory contacts: {dir_count}")

    print("Seeding organizer login accounts (directory → users)…")
    org_accounts = await seed_organizer_accounts(db)
    print(f"  Organizer accounts created: {org_accounts} (password: {ORGANIZER_ACCOUNT_PASSWORD})")

    await db.commit()
    print("Seed complete.")
    print()
    print("Login credentials:")
    for role, password in roles_passwords:
        print(f"  seed_{role.value} / {password}")
    print(f"  org_<serial> / {ORGANIZER_ACCOUNT_PASSWORD}  (e.g. org_1, org_99)")


async def main() -> None:
    engine = create_async_engine(settings.DATABASE_URL, echo=False)
    session_factory = async_sessionmaker(engine, expire_on_commit=False)
    async with session_factory() as db:
        await seed(db)
    await engine.dispose()


if __name__ == "__main__":
    asyncio.run(main())
