"""
Synthetic seed data for development.
RULE: No real PII. All names, phone numbers, and identifiers are generated by Faker.
Run: python -m seed.seed  (from the backend/ directory with DATABASE_URL set)
"""

import asyncio
import random

from faker import Faker
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine

from app.config import settings
from app.models.enums import (
    BloodGroupEnum,
    ComponentTypeEnum,
    UserRoleEnum,
)
from app.models.facility import Facility
from app.models.auth import User
from app.models.audit import FeatureFlag
from app.models.stock import AlertThreshold as AlertThresholdModel
from app.services.auth import hash_password

fake = Faker("en_IN")
random.seed(42)

BLOOD_GROUPS = list(BloodGroupEnum)
COMPONENT_TYPES = list(ComponentTypeEnum)


async def seed(db: AsyncSession) -> None:
    print("Seeding facilities…")
    facility = Facility(
        name="District Hospital & Red Cross Blood Bank, Durg",
        facility_code="RKDURG",
        type="blood_bank",
        address="Civil Lines, Durg, Chhattisgarh 491001",
        district="Durg",
        state="Chhattisgarh",
        phone="07788-123456",
        is_active=True,
    )
    db.add(facility)
    await db.flush()

    print("Seeding users (one per role)…")
    roles_passwords = [
        (UserRoleEnum.ADMIN, "admin123"),
        (UserRoleEnum.MEDICAL_OFFICER, "medofficer123"),
        (UserRoleEnum.LAB_TECH, "labtech123"),
        (UserRoleEnum.PHLEBOTOMIST, "phlebo123"),
        (UserRoleEnum.INVENTORY_OFFICER, "inventory123"),
        (UserRoleEnum.ORGANIZER, "organizer123"),
        (UserRoleEnum.DONOR, "donor123"),
        (UserRoleEnum.CITIZEN_READ, "citizen123"),
    ]
    users: dict[UserRoleEnum, User] = {}
    for role, password in roles_passwords:
        user = User(
            facility_id=facility.id if role not in (UserRoleEnum.ORGANIZER, UserRoleEnum.DONOR, UserRoleEnum.CITIZEN_READ) else None,
            role=role,
            username=f"seed_{role.value}",
            email=f"seed_{role.value}@rakt.local",
            phone=fake.phone_number()[:20],
            hashed_password=hash_password(password),
            display_name=f"Seed {role.value.replace('_', ' ').title()}",
            is_active=True,
        )
        db.add(user)
        users[role] = user
    await db.flush()

    print("Seeding alert thresholds…")
    for bg in BLOOD_GROUPS:
        for ct in COMPONENT_TYPES:
            threshold = AlertThresholdModel(
                facility_id=facility.id,
                blood_group=bg,
                component_type=ct,
                low_stock_qty=2,
                near_expiry_days=3,
                updated_by=users[UserRoleEnum.ADMIN].id,
            )
            db.add(threshold)

    print("Seeding barcode sequence…")
    await db.execute(
        text(
            "INSERT INTO barcode_sequences (facility_id, last_seq) "
            "VALUES (:fid, 0) ON CONFLICT DO NOTHING"
        ),
        {"fid": str(facility.id)},
    )

    print("Verifying feature flag…")
    flag_result = await db.execute(
        text("SELECT is_enabled FROM feature_flags WHERE name='wallet_enabled'")
    )
    flag = flag_result.scalar_one_or_none()
    if flag is None:
        db.add(FeatureFlag(
            name="wallet_enabled",
            is_enabled=False,
            description="Blood Credit Wallet — requires clinical/legal sign-off.",
        ))

    await db.commit()
    print("Seed complete.")
    print()
    print("Login credentials:")
    for role, password in roles_passwords:
        print(f"  seed_{role.value} / {password}")


async def main() -> None:
    engine = create_async_engine(settings.DATABASE_URL, echo=False)
    session_factory = async_sessionmaker(engine, expire_on_commit=False)
    async with session_factory() as db:
        await seed(db)
    await engine.dispose()


if __name__ == "__main__":
    asyncio.run(main())
